stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "taskflow.settings.development"

  POSTGRES_DB: "taskflow"
  POSTGRES_USER: "taskflow"
  POSTGRES_PASSWORD: "taskflow"

  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONUNBUFFERED: "1"

  PYTHONPATH: "$CI_PROJECT_DIR/src"

  CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'
  CELERY_RESULT_BACKEND: 'django-db'

cache:
  key:
    files:
      - poetry.lock

  paths:
    - .cache/pip
    - .cache/pypoetry

  policy: pull-push

before_script:
  - echo "$DOTENV_CONTENT" > src/taskflow/.env
  - pip install poetry==1.8.5
  - poetry install --no-interaction --no-ansi
  - poetry run python src/manage.py makemigrations
  - poetry run python src/manage.py migrate
  - poetry run python src/manage.py migrate django_celery_results

test_job:
  stage: test

  image: python:3.12

  services:
    - name: postgres:16
      alias: db

    - name: redis:7
      alias: redis

    - name: rabbitmq:3.12-management-alpine
      alias: rabbitmq

  script:
    - poetry run celery -A taskflow worker --loglevel=info &
    - sleep 10
    - poetry run python src/manage.py test taskflow --verbosity=2
