# Generated by Django 5.2.11 on 2026-05-16 10:50

import django.db.models.deletion
import django.utils.timezone
import taskflow.accounts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="avatar"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Name shown to other team members",
                max_length=150,
                null=True,
                verbose_name="display name",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_notifications_enabled",
            field=models.BooleanField(default=True, verbose_name="email notifications"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="invitation_accepted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="invitation accepted at"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="invited by",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="online status"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last activity"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[taskflow.accounts.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
    ]
