# Generated by Django 5.2.11 on 2026-05-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="invitation_accepted_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="invited_by",
        ),
    ]
