# Generated by Django 5.2.11 on 2026-06-06 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0004_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("join_request", "Join Request"),
                            ("join_approved", "Join Approved"),
                            ("join_rejected", "Join Rejected"),
                            ("invitation", "Invitation"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="action url"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="unread",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_notifications",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_notifications",
                        to="companies.invitation",
                        verbose_name="invitation",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_e285de_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_ae6ed6_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
    ]
