# Generated by Django 5.2.11 on 2026-07-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0006_alter_invitation_invitation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The visible name of the board. For example: "Project Alpha" or "Marketing Plan".',
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="A unique URL-friendly identifier for the board. Can contain Persian characters.",
                        max_length=64,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. A short description about the purpose or content of the board.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="boards/cover/",
                        verbose_name="cover",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("workspace", "Workspace"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active board"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_boards",
                        to="companies.company",
                        verbose_name="company board",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created and owns this board. Cannot be deleted while the board exists.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_boards",
                        to="companies.membership",
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "admin"),
                            ("Membership", "membership"),
                            ("Viewer", "viewer"),
                        ],
                        default="Membership",
                        max_length=11,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_memberships",
                        to="boards.board",
                        verbose_name="board",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_memberships",
                        to="companies.membership",
                        verbose_name="membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board Membership",
                "verbose_name_plural": "Board Memberships",
            },
        ),
        migrations.AddField(
            model_name="board",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have access to this board besides the owner.",
                related_name="member_boards",
                through="boards.BoardMembership",
                to="companies.membership",
                verbose_name="member board",
            ),
        ),
        migrations.AddIndex(
            model_name="boardmembership",
            index=models.Index(fields=["board"], name="boards_boar_board_i_5ac1e2_idx"),
        ),
        migrations.AddIndex(
            model_name="boardmembership",
            index=models.Index(
                fields=["membership"], name="boards_boar_members_c0b261_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardmembership",
            constraint=models.UniqueConstraint(
                fields=("board", "membership"), name="unique_membership_per_board"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["company"], name="boards_boar_company_0d32a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["name"], name="boards_boar_name_110f36_idx"),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(fields=["owner"], name="boards_boar_owner_i_f9f6ff_idx"),
        ),
    ]
