# Generated by Django 5.2.11 on 2026-05-22 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The visible name of the board. For example: "Project Alpha" or "Marketing Plan".',
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="A unique URL-friendly identifier for the board. Can contain Persian characters.",
                        max_length=64,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. A short description about the purpose or content of the board.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active board"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who have access to this board besides the owner.",
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="member board",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created and owns this board. Cannot be deleted while the board exists.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_boards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "slug"], name="boards_boar_name_65fe39_idx"
                    ),
                    models.Index(
                        fields=["owner"], name="boards_boar_owner_i_f9f6ff_idx"
                    ),
                ],
            },
        ),
    ]
