# Generated by Django 5.2.11 on 2026-04-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the list.",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The position of the list within the board. Lower numbers appear first.",
                        verbose_name="position",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        help_text="The board to which this list belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="boards.board",
                        verbose_name="board",
                    ),
                ),
            ],
            options={
                "verbose_name": "List",
                "verbose_name_plural": "Lists",
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["board", "position"],
                        name="boards_list_board_i_ada2a2_idx",
                    )
                ],
                "unique_together": {("board", "position")},
            },
        ),
    ]
