# Generated by Django 5.2.11 on 2026-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        ("companies", "0006_alter_invitation_invitation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("viewer", "Viewer"),
                ],
                default="member",
                max_length=11,
                verbose_name="role",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_board_name_per_company"
            ),
        ),
    ]
