# Generated by Django 5.2.11 on 2026-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active board"),
        ),
    ]
