# Generated by Django 5.2.11 on 2026-05-22 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="website"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/logo/",
                        verbose_name="image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "admin"), ("Member", "member")],
                        default="Member",
                        max_length=7,
                        verbose_name="role",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                through="companies.Membership",
                through_fields=("company", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "company"], name="companies_m_user_id_24517c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["role"], name="companies_m_role_c549f0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "company")},
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="companies_c_slug_45751b_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["owner"], name="companies_c_owner_i_f8927e_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active"], name="companies_c_is_acti_03043b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["created_at"], name="companies_c_created_301a54_idx"
            ),
        ),
    ]
