# Generated by Django 5.2.11 on 2026-05-20 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="company",
            name="companies_c_name_22cebd_idx",
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="companies_c_name_2d8260_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="companies_c_slug_45751b_idx"),
        ),
    ]
