# Generated by Django 5.2.11 on 2026-05-24 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["owner", "is_active"], name="companies_c_owner_i_443b40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["id", "owner"], name="companies_c_id_ef583c_idx"
            ),
        ),
    ]
