# Generated by Django 5.2.11 on 2026-05-24 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_companies_c_owner_i_443b40_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["company_id", "user_id"], name="companies_m_company_a3adb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user_id"], name="companies_m_user_id_b8199c_idx"
            ),
        ),
    ]
