# Generated by Django 5.2.11 on 2026-05-22 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_company_companies_c_name_22cebd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=128, unique=True, verbose_name="name"),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "admin"), ("Member", "member")],
                        default="Member",
                        max_length=7,
                        verbose_name="role",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "verbose_name_plural": "memberships",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies",
                through="companies.Membership",
                through_fields=("company", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "company"], name="companies_m_user_id_24517c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["role"], name="companies_m_role_c549f0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "company")},
        ),
    ]
