# Generated by Django 5.2.11 on 2026-05-26 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_membership_companies_m_company_a3adb8_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "admin"), ("Member", "member")],
                        default="Member",
                        max_length=7,
                        verbose_name="role",
                    ),
                ),
                (
                    "invitation_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Invitation"),
                            ("direct", "Direct Invitation"),
                            ("request", "Join Request"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="invitation type",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=100, unique=True, verbose_name="token"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited user",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
                "indexes": [
                    models.Index(fields=["token"], name="companies_i_token_70f398_idx"),
                    models.Index(
                        fields=["email", "status"], name="companies_i_email_a3213b_idx"
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="companies_i_company_3e26c3_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="companies_i_expires_b7636c_idx"
                    ),
                    models.Index(
                        fields=["invitation_type"],
                        name="companies_i_invitat_e0e62b_idx",
                    ),
                ],
                "unique_together": {("email", "company", "status")},
            },
        ),
    ]
