# Generated by Django 5.2.11 on 2026-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_invitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("Admin", "admin"), ("Member", "member"), ("Owner", "owner")],
                default="Member",
                max_length=7,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("Admin", "admin"), ("Member", "member"), ("Owner", "owner")],
                default="Member",
                max_length=7,
                verbose_name="role",
            ),
        ),
    ]
