# Generated by Django 5.2.11 on 2026-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_invitation_role_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="invitation_type",
            field=models.CharField(
                choices=[
                    ("email", "Email Invitation"),
                    ("direct", "Direct Invitation"),
                    ("request", "Join Request"),
                    ("member_invite", "Member Invite"),
                ],
                default="email",
                max_length=14,
                verbose_name="invitation type",
            ),
        ),
    ]
